// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://xkyhvkuahdvvlwjgnipt.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhreWh2a3VhaGR2dmx3amduaXB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNDE4NTIsImV4cCI6MjA2ODgxNzg1Mn0.tMMLA3Ani8jSCemtZpCa_AJ1pwvBhV4gswNVRmOt3Ys';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  },
);
